<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Provider;

class ProviderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $providers = [
            [
                'code' => 'GT-TT',
                'name' => 'Garage Thắng Trường',
                'business_name' => 'Công ty TNHH Thắng Trường Auto',
                'tax_code' => '0123456789',
                'contact_person' => 'Trần Văn Thắng',
                'phone' => '0912345678',
                'email' => 'thangtruong@garage.com',
                'address' => '456 Đường Quốc Lộ 1A, Phường Linh Xuân, Thủ Đức, TP.HCM',
                'website' => 'https://thangtruongauto.vn',
                'bank_name' => 'Vietcombank',
                'bank_account' => '0123456789',
                'bank_branch' => 'Chi nhánh Thủ Đức',
                'service_types' => 'repair,maintenance,bodywork,paint',
                'specializations' => 'engine,electrical,bodywork,painting,inspection',
                'commission_rate' => 15.00,
                'payment_terms' => 15,
                'credit_limit' => 50000000,
                'payment_method' => 'transfer',
                'rating' => 4.80,
                'completed_orders' => 250,
                'average_completion_time' => 48.5,
                'status' => 'active',
                'notes' => 'Đối tác chính, có kinh nghiệm sửa chữa lâu năm',
            ],
            [
                'code' => 'GT-01',
                'name' => 'Garage Minh Tuấn',
                'business_name' => 'Xưởng Sửa Chữa Minh Tuấn',
                'tax_code' => '0123456790',
                'contact_person' => 'Nguyễn Minh Tuấn',
                'phone' => '0923456789',
                'email' => 'minhtuan@garage.com',
                'address' => '789 Đường Võ Văn Ngân, Linh Chiểu, Thủ Đức, TP.HCM',
                'bank_name' => 'Techcombank',
                'bank_account' => '9876543210',
                'bank_branch' => 'Chi nhánh Thủ Đức',
                'service_types' => 'repair,parts',
                'specializations' => 'engine,transmission,suspension',
                'commission_rate' => 18.00,
                'payment_terms' => 30,
                'credit_limit' => 30000000,
                'payment_method' => 'transfer',
                'rating' => 4.50,
                'completed_orders' => 180,
                'average_completion_time' => 52.0,
                'status' => 'active',
                'notes' => 'Chuyên về động cơ và hộp số',
            ],
            [
                'code' => 'GT-02',
                'name' => 'Garage Hoàng Long',
                'business_name' => 'Công ty CP Hoàng Long Auto',
                'tax_code' => '0123456791',
                'contact_person' => 'Trần Hoàng Long',
                'phone' => '0934567890',
                'email' => 'hoanglong@garage.com',
                'address' => '321 Đường Nguyễn Văn Linh, Tân Phú, Quận 7, TP.HCM',
                'bank_name' => 'VPBank',
                'bank_account' => '1122334455',
                'bank_branch' => 'Chi nhánh Quận 7',
                'service_types' => 'bodywork,paint',
                'specializations' => 'bodywork,painting,dent_repair',
                'commission_rate' => 20.00,
                'payment_terms' => 7,
                'credit_limit' => 20000000,
                'payment_method' => 'transfer',
                'rating' => 4.30,
                'completed_orders' => 120,
                'average_completion_time' => 96.0,
                'status' => 'active',
                'notes' => 'Chuyên sơn gò thân xe',
            ],
            [
                'code' => 'GT-03',
                'name' => 'Garage Thành Đạt',
                'business_name' => 'Xưởng Ô Tô Thành Đạt',
                'tax_code' => '0123456792',
                'contact_person' => 'Lê Thành Đạt',
                'phone' => '0945678901',
                'email' => 'thanhdat@garage.com',
                'address' => '654 Đường Phạm Văn Đồng, Hiệp Bình Chánh, Thủ Đức, TP.HCM',
                'bank_name' => 'ACB',
                'bank_account' => '5544332211',
                'bank_branch' => 'Chi nhánh Thủ Đức',
                'service_types' => 'repair,maintenance,inspection',
                'specializations' => 'electrical,aircon,inspection',
                'commission_rate' => 16.00,
                'payment_terms' => 30,
                'credit_limit' => 25000000,
                'payment_method' => 'transfer',
                'rating' => 4.60,
                'completed_orders' => 150,
                'average_completion_time' => 36.0,
                'status' => 'active',
                'notes' => 'Chuyên về điện, điện tử và đăng kiểm',
            ],
            [
                'code' => 'BH-01',
                'name' => 'Bảo Hiểm Bảo Việt',
                'business_name' => 'Tổng Công ty Bảo Hiểm Bảo Việt',
                'tax_code' => '0100110653',
                'contact_person' => 'Nguyễn Thị Mai',
                'phone' => '1900558899',
                'email' => 'auto@baoviet.com.vn',
                'address' => '8 Lê Thánh Tôn, Quận 1, TP.HCM',
                'website' => 'https://www.baoviet.com.vn',
                'bank_name' => 'Vietcombank',
                'bank_account' => '0123456789012',
                'bank_branch' => 'Hội Sở Chính',
                'service_types' => 'insurance',
                'specializations' => 'vehicle_insurance',
                'commission_rate' => 10.00,
                'payment_terms' => 60,
                'credit_limit' => 100000000,
                'payment_method' => 'transfer',
                'rating' => 4.70,
                'status' => 'active',
                'notes' => 'Đối tác bảo hiểm chính',
            ],
            [
                'code' => 'BH-02',
                'name' => 'Bảo Hiểm PVI',
                'business_name' => 'Tổng Công ty Bảo Hiểm PVI',
                'tax_code' => '0100105765',
                'contact_person' => 'Trần Văn Bình',
                'phone' => '1900545481',
                'email' => 'auto@pvi.com.vn',
                'address' => '22 Ngô Quyền, Quận 5, TP.HCM',
                'website' => 'https://www.pvi.com.vn',
                'bank_name' => 'Techcombank',
                'bank_account' => '9876543210123',
                'bank_branch' => 'Hội Sở Chính',
                'service_types' => 'insurance',
                'specializations' => 'vehicle_insurance',
                'commission_rate' => 12.00,
                'payment_terms' => 45,
                'credit_limit' => 80000000,
                'payment_method' => 'transfer',
                'rating' => 4.50,
                'status' => 'active',
                'notes' => 'Đối tác bảo hiểm phụ',
            ],
        ];

        foreach ($providers as $providerData) {
            Provider::updateOrCreate(
                ['code' => $providerData['code']],
                $providerData
            );
        }

        $this->command->info('Đã tạo ' . count($providers) . ' đối tác thành công!');
    }
}
